const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    SET_FORGE_ACCESS: 'SET_FORGE_ACCESS',
    SET_VIEWER_ACCESS: 'SET_VIEWER_ACCESS'
}

export default ACTIONS